### PR TITLE
Development

### PR DESCRIPTION
**Pull request by MrObele**
On development stage @talihomz

### CODE REVIEW

**Comment by MrObele** [comment]
@talihomz, project completed on ruby enumerables here is the review guidelines link `https://docs.google.com/document/d/17TOutEv23v8aYOmlZMvkheqDVHUCz7L6V_jMFQL7jbY/edit`

**Comment by talihomz** [comment]
Hi @MrObele @uzorjchibuzor

This was awesomely done! 
Is there a solution missing for the bubble-sort exercise? SortBy?

Also, you can use a linter such as [RuboCop](https://github.com/rubocop-hq/rubocop) to catch syntax errors or use of best practices. When I ran `rubocop -a` on your code, here is what I found.

chibu-review

Add the `sort-by` exercise, then I can give a go ahead. Great work guys!

**Comment by uzorjchibuzor** [comment]
How could we have missed that? Will get it done today. Is there a need to submit another review request?

**Comment by talihomz** [comment]
Nope. Just here so that we can handle communication easier. Sounds ok?

**Comment by uzorjchibuzor** [comment]
@talihomz pushed another commit. Thanks.

EDIT: Couldn't get Rubocop to work, here is what I am getting

image
 
Read the doc on github and could not find out what went wrong

**Comment by talihomz** [comment]
@uzorjchibuzor probably installed it wrong. I haven'r seen such an error in my setup so far. I'l try see if I can solve for it and let you know.

Otherwise, I had a look at the sort-by example, looks great! Its a 👍 from me.

**Review by uzorjchibuzor — APPROVED** [review]

**Pull request merged**
